### ISSUE TITLE
add soname versioning support

### ISSUE THREAD

**Issue by q66** [canonical/libco#7]
Right now this produces a `libco.so` which is incompatible with distribution packaging (`libco.so` should be a symlink to the versioned files); while distros can add versioning soname themselves this potentially leads to differences and would be best to have upstream.

**Comment by q66** [comment]
If you do this, don't forget to also add the appropriate linker flag so that projects linking against this can properly enforce it.

**Comment by q66** [comment]
Also, while doing this, the makefile should respect global `CFLAGS` and `LDFLAGS`, it does not right now.

**Comment by freeekanayaka** [comment]
Isn't this fixed by the very latest commits in the last days? See the current Makefile:

https://github.com/canonical/libco/blob/master/Makefile

it creates ```libco.so``` as a symlink. I can add support for ```CFLAGS``` and ```LDFLAGS```.

**Comment by q66** [comment]
It's not fixed, because of what I linked above.

**Comment by q66** [comment]
The fix should be something like doing

```
$(CC) $(CFLAGS) -c -Wall -fpic libco.c -DLIBCO_MP
$(CC) $(LDFLAGS) -shared -Wl,-soname,libco.so.$(MAJ) -o libco.so.$(MIN) libco.o
```

Then create symlinks for `libco.so` and `libco.so.$(MAJ)` in the `install` target.

**Comment by freeekanayaka** [comment]
@q66 does the above PR look fine to you? I placed ```CFLAGS``` and ```LDFLAGS``` at the end as I think that way they also take precedence.

**Comment by q66** [comment]
Why would they take precedence? These are flags you always want to have in order to be able to build the project correctly, so the user should never override them.

**Comment by q66** [comment]
Also `LDFLAGS` should be passed in addition to `CFLAGS` when calling the compiler for linking, with `CFLAGS` coming first, then `LDFLAGS`. That's how Make implicit rules work and that's how explicit ones should also work.

**Comment by freeekanayaka** [comment]
iirc that automake puts ```CFLAGS```/```LDFLAGS``` last, but I might be off. Changed as you proposed.

**Comment by q66** [comment]
Well, ultimately it does not matter much (spurious flags mean breakage on user side), so either way is probably fine... but yeah, looks good to me now. With this distributions can apply things like hardening flags as well as do less work in their packaging recipes overall.
